---
- name: install python3 
  hosts: elasticsearch
  gather_facts: false
  tasks:
  - name: install python3
    raw: apt install -y python3 python3-pip

- name: Install Java and elasticsearch
  hosts: elasticsearch
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  tasks:
  - debug: var=ansible_host
  - name: install java
    import_role:
      name: java

- name: Install Elasticsearch
  hosts: elasticsearch
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  tasks:
  - debug: var=ansible_host
  - name: Elastick import_role
    import_role:
      name: elastic-role
 
- name: Install Kibana
  hosts: elasticsearch
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  tasks:
  - debug: var=ansible_host
  - name: instal kibana
    import_role:
      name: kibana-role

    
